
# html lang
language: zh-CN

# main menu navigation 导航菜单显示
menu:
- page: home
  url: /
  icon: fa-home
- page: demo
  url: https://github.com/lizehongss/demo_show
  icon: fa-code
- page: about
  url: /about
  icon: fa-user
- page: music
  url: /
  icon: fa-music
# Content 内容显示
excerpt_link: Read More
excerpt_length: 100
# Sidebar 侧栏分类
# sidebar 左右
widgets:
- category ##文章分类
- tag ##标签 
- archives ##文章归档

# widget behavioe

show_count: true ##显示分类和归档文章数目
archive_type: yearly  ##归档类型yearly or monthly

# bottom nav 底部导航 
# 图标格式可使用https://forkawesome.github.io/Fork-Awesome/icons/查询

social:
# - url: #
#   title: #
#   icon: #
- url: https://github.com/lizehongss
  title: Follow me
  icon: fa-github

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/fork-awesome.min.css ##图标样式
- /css/zhl.css ## 自定义样式，会覆盖 

# scripts loaded in the end of the body
scripts:
- /js/zhl.js 
- /js/bj.js ##背景动画
